// ============================================================
// lib/services/mock_data.dart
// PRISM AI — Enhanced Mock Data Layer
// 60+ realistic Pakistani providers across Karachi, Islamabad, Lahore
// Fully compatible with AiEngine filtering & ranking
// ============================================================

import 'package:flutter/material.dart';
import '../models/provider_model.dart';

class MockData {
  // ─────────────────────────────────────────────────────────
  // SERVICE CATEGORIES
  // ─────────────────────────────────────────────────────────
  static const List<Map<String, dynamic>> categories = [
    {
      'icon': Icons.ac_unit_rounded,
      'label': 'AC Repair',
      'color': Color(0xFF00C2D4),
    },
    {
      'icon': Icons.electrical_services_rounded,
      'label': 'Electrician',
      'color': Color(0xFFFFB347),
    },
    {
      'icon': Icons.plumbing_rounded,
      'label': 'Plumbing',
      'color': Color(0xFF4FC3F7),
    },
    {
      'icon': Icons.face_retouching_natural_rounded,
      'label': 'Beautician',
      'color': Color(0xFFFF80AB),
    },
    {
      'icon': Icons.menu_book_rounded,
      'label': 'Tutor',
      'color': Color(0xFF6C4FD6),
    },
    {
      'icon': Icons.cleaning_services_rounded,
      'label': 'Cleaning',
      'color': Color(0xFF66BB6A),
    },
    {
      'icon': Icons.build_rounded,
      'label': 'Mechanic',
      'color': Color(0xFFFF7043),
    },
    {
      'icon': Icons.local_shipping_rounded,
      'label': 'Shifting',
      'color': Color(0xFF185FA5),
    },
  ];

  // ─────────────────────────────────────────────────────────
  // SUPPORTED CITIES
  // ─────────────────────────────────────────────────────────
  static const List<String> supportedCities = [
    'Karachi',
    'Islamabad',
    'Lahore',
  ];

  // ─────────────────────────────────────────────────────────
  // CITY ALIASES  (lowercase keyword → canonical city)
  // Used by AiEngine._extractLocation()
  // ─────────────────────────────────────────────────────────
  static const Map<String, String> cityAliases = {
    // ── Karachi ─────────────────────────────────────────
    'karachi': 'Karachi',
    'khi': 'Karachi',
    'dha': 'Karachi',
    'dha karachi': 'Karachi',
    'clifton': 'Karachi',
    'gulshan': 'Karachi',
    'gulshan iqbal': 'Karachi',
    'nazimabad': 'Karachi',
    'north nazimabad': 'Karachi',
    'johar': 'Karachi',
    'gulistan johar': 'Karachi',
    'malir': 'Karachi',
    'korangi': 'Karachi',
    'saddar': 'Karachi',
    'bahadurabad': 'Karachi',
    'pechs': 'Karachi',
    'scheme 33': 'Karachi',
    'orangi': 'Karachi',
    'landhi': 'Karachi',
    'shah faisal': 'Karachi',
    'tariq road': 'Karachi',
    'boat basin': 'Karachi',
    'defence': 'Karachi',
    'liaquatabad': 'Karachi',

    // ── Islamabad ────────────────────────────────────────
    'islamabad': 'Islamabad',
    'isb': 'Islamabad',
    'g-13': 'Islamabad',
    'g-10': 'Islamabad',
    'g-11': 'Islamabad',
    'g-9': 'Islamabad',
    'g-6': 'Islamabad',
    'f-10': 'Islamabad',
    'f-7': 'Islamabad',
    'f-6': 'Islamabad',
    'f-8': 'Islamabad',
    'f-11': 'Islamabad',
    'e-11': 'Islamabad',
    'e-7': 'Islamabad',
    'i-8': 'Islamabad',
    'i-10': 'Islamabad',
    'i-14': 'Islamabad',
    'bahria': 'Islamabad',
    'bahria town': 'Islamabad',
    'dha islamabad': 'Islamabad',
    'rawalpindi': 'Islamabad',
    'pindi': 'Islamabad',
    'rwp': 'Islamabad',
    'blue area': 'Islamabad',
    'pwd': 'Islamabad',
    'soan garden': 'Islamabad',

    // ── Lahore ───────────────────────────────────────────
    'lahore': 'Lahore',
    'lhr': 'Lahore',
    'gulberg': 'Lahore',
    'dha lahore': 'Lahore',
    'model town': 'Lahore',
    'johar town': 'Lahore',
    'defence lahore': 'Lahore',
    'iqbal town': 'Lahore',
    'garden town': 'Lahore',
    'bahria lahore': 'Lahore',
    'wapda town': 'Lahore',
    'cavalry ground': 'Lahore',
    'cantt': 'Lahore',
    'lahore cantt': 'Lahore',
    'township': 'Lahore',
    'faisal town': 'Lahore',
    'valencia': 'Lahore',
    'thokar': 'Lahore',
    'ferozepur road': 'Lahore',
    'mall road': 'Lahore',
    'raiwind': 'Lahore',
  };

  // ─────────────────────────────────────────────────────────
  // AI UNDERSTANDING (legacy — kept for backward compat)
  // ─────────────────────────────────────────────────────────
  static const Map<String, dynamic> aiUnderstanding = {
    'service': 'AC Repair',
    'location': 'G-13, Islamabad',
    'urgency': 'High',
    'time': 'Tomorrow Morning',
    'budget': 'Medium Sensitivity',
    'confidence': 92,
  };

  // ─────────────────────────────────────────────────────────
  // BOOKING TIMELINE TEMPLATE
  // TrackingScreen drives live state from this seed
  // ─────────────────────────────────────────────────────────
  static const List<Map<String, dynamic>> bookingTimeline = [
    {'label': 'Request Received', 'done': true},
    {'label': 'AI Analysis Complete', 'done': true},
    {'label': 'Provider Matched', 'done': true},
    {'label': 'Booking Confirmed', 'done': false},
    {'label': 'Technician Assigned', 'done': false},
    {'label': 'En Route to Location', 'done': false},
    {'label': 'Service In Progress', 'done': false},
    {'label': 'Completed', 'done': false},
  ];

  // ═════════════════════════════════════════════════════════
  //  PROVIDER POOL  —  60+ realistic Pakistani providers
  //  Sorted: City → Service Category
  // ═════════════════════════════════════════════════════════
  static const List<ProviderModel> providers = [
    // ╔═══════════════════════════════════════╗
    // ║  KARACHI — AC REPAIR  (6)            ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'Ustad Ali AC Services',
      city: 'Karachi',
      serviceCategory: 'AC Repair',
      rating: 4.8,
      reviews: 247,
      distance: '1.9 km',
      distanceKm: 1.9,
      onTime: 96,
      price: 2500,
      available: '09:00 AM',
      cancellationRate: 3,
      reliabilityScore: 97,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Specialized in all AC brands',
        'Near-perfect reliability score',
        'Low cancellation rate (3%)',
        'Same-day gas charging available',
      ],
    ),
    ProviderModel(
      name: 'CoolTech Solutions',
      city: 'Karachi',
      serviceCategory: 'AC Repair',
      rating: 4.6,
      reviews: 189,
      distance: '3.2 km',
      distanceKm: 3.2,
      onTime: 91,
      price: 2200,
      available: '10:30 AM',
      cancellationRate: 8,
      reliabilityScore: 91,
      badge: 'Budget Friendly',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Most affordable AC repair',
        'Inverter & split AC expert',
        'Certified Samsung technician',
        'Free diagnostic visit',
      ],
    ),
    ProviderModel(
      name: 'Rafiq AirFlow Experts',
      city: 'Karachi',
      serviceCategory: 'AC Repair',
      rating: 4.5,
      reviews: 134,
      distance: '1.4 km',
      distanceKm: 1.4,
      onTime: 88,
      price: 2800,
      available: '11:00 AM',
      cancellationRate: 12,
      reliabilityScore: 88,
      badge: 'Nearest',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Closest provider to you',
        'Premium-tier AC service',
        'Senior certified technician',
        'Window & split AC specialist',
      ],
    ),
    ProviderModel(
      name: 'Chill Zone AC & Repair',
      city: 'Karachi',
      serviceCategory: 'AC Repair',
      rating: 4.3,
      reviews: 78,
      distance: '4.0 km',
      distanceKm: 4.0,
      onTime: 85,
      price: 1800,
      available: '08:00 AM',
      cancellationRate: 14,
      reliabilityScore: 85,
      badge: 'Earliest Slot',
      badgeColor: Color(0xFF66BB6A),
      reasons: [
        'Earliest available (8:00 AM)',
        'Most affordable in DHA',
        'Gas refill specialist',
        'Quick 1-hour response',
      ],
    ),
    ProviderModel(
      name: 'Hasnain Cooling Services',
      city: 'Karachi',
      serviceCategory: 'AC Repair',
      rating: 4.7,
      reviews: 203,
      distance: '2.6 km',
      distanceKm: 2.6,
      onTime: 93,
      price: 2400,
      available: '10:00 AM',
      cancellationRate: 6,
      reliabilityScore: 93,
      badge: 'Highly Reliable',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Daikin & Gree brand expert',
        'Strong on-time record (93%)',
        'Cooling performance check included',
        'Gulshan & Johar area specialist',
      ],
    ),
    ProviderModel(
      name: 'Arctic Breeze AC',
      city: 'Karachi',
      serviceCategory: 'AC Repair',
      rating: 4.4,
      reviews: 91,
      distance: '5.1 km',
      distanceKm: 5.1,
      onTime: 87,
      price: 2000,
      available: '12:00 PM',
      cancellationRate: 13,
      reliabilityScore: 87,
      badge: 'Good Value',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'PCB & compressor repair',
        'Annual maintenance contracts',
        'Reliable budget option',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  KARACHI — ELECTRICIAN  (5)          ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'Imtiaz Bright Spark Electric',
      city: 'Karachi',
      serviceCategory: 'Electrician',
      rating: 4.9,
      reviews: 318,
      distance: '1.3 km',
      distanceKm: 1.3,
      onTime: 97,
      price: 1800,
      available: '08:30 AM',
      cancellationRate: 2,
      reliabilityScore: 97,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Highest rated electrician in area',
        'Licensed & fully insured',
        'Surge protection & DB specialist',
        'Near-perfect punctuality (97%)',
      ],
    ),
    ProviderModel(
      name: 'PowerFix KHI',
      city: 'Karachi',
      serviceCategory: 'Electrician',
      rating: 4.5,
      reviews: 156,
      distance: '2.7 km',
      distanceKm: 2.7,
      onTime: 90,
      price: 1500,
      available: '09:30 AM',
      cancellationRate: 10,
      reliabilityScore: 90,
      badge: 'Budget Friendly',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Most affordable electrician',
        'Wiring & panel expert',
        'Inverter & UPS installations',
      ],
    ),
    ProviderModel(
      name: 'Farhan Electricals',
      city: 'Karachi',
      serviceCategory: 'Electrician',
      rating: 4.6,
      reviews: 172,
      distance: '2.1 km',
      distanceKm: 2.1,
      onTime: 92,
      price: 1700,
      available: '09:00 AM',
      cancellationRate: 8,
      reliabilityScore: 92,
      badge: 'Highly Reliable',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Industrial & home wiring expert',
        'KESC approved technician',
        'Emergency call-out available',
        'DHA & Clifton specialist',
      ],
    ),
    ProviderModel(
      name: 'VoltMax Solutions',
      city: 'Karachi',
      serviceCategory: 'Electrician',
      rating: 4.3,
      reviews: 87,
      distance: '3.8 km',
      distanceKm: 3.8,
      onTime: 85,
      price: 1400,
      available: '10:00 AM',
      cancellationRate: 15,
      reliabilityScore: 85,
      badge: 'Budget Option',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Lowest price in area',
        'MCB & fuse box repairs',
        'Solar panel wiring available',
      ],
    ),
    ProviderModel(
      name: 'Nadeem Electric Works',
      city: 'Karachi',
      serviceCategory: 'Electrician',
      rating: 4.7,
      reviews: 241,
      distance: '1.8 km',
      distanceKm: 1.8,
      onTime: 94,
      price: 2000,
      available: '08:00 AM',
      cancellationRate: 5,
      reliabilityScore: 94,
      badge: 'Premium',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Premium certified electrician',
        'Fastest response time',
        'Gulshan & Nazimabad coverage',
        '5-year wiring warranty',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  KARACHI — PLUMBING  (5)             ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'Aamir AquaFix Plumbing',
      city: 'Karachi',
      serviceCategory: 'Plumbing',
      rating: 4.7,
      reviews: 214,
      distance: '2.0 km',
      distanceKm: 2.0,
      onTime: 94,
      price: 1600,
      available: '07:30 AM',
      cancellationRate: 5,
      reliabilityScore: 94,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Emergency plumbing specialist',
        'Motor & water pump expert',
        'Earliest morning slot (7:30 AM)',
        'Leak detection & repair',
      ],
    ),
    ProviderModel(
      name: 'Pipe Masters KHI',
      city: 'Karachi',
      serviceCategory: 'Plumbing',
      rating: 4.4,
      reviews: 128,
      distance: '3.5 km',
      distanceKm: 3.5,
      onTime: 86,
      price: 1300,
      available: '09:00 AM',
      cancellationRate: 14,
      reliabilityScore: 86,
      badge: 'Budget Friendly',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Most affordable plumber',
        'Drain cleaning & unblocking',
        'Bathroom fitting specialist',
      ],
    ),
    ProviderModel(
      name: 'Tariq & Sons Plumbers',
      city: 'Karachi',
      serviceCategory: 'Plumbing',
      rating: 4.6,
      reviews: 167,
      distance: '1.6 km',
      distanceKm: 1.6,
      onTime: 91,
      price: 1800,
      available: '08:00 AM',
      cancellationRate: 8,
      reliabilityScore: 91,
      badge: 'Nearest',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Closest plumber to you',
        'Family business — trusted since 2004',
        'Complete bathroom renovation',
        'WASA pipeline expert',
      ],
    ),
    ProviderModel(
      name: 'FlowRight Plumbing',
      city: 'Karachi',
      serviceCategory: 'Plumbing',
      rating: 4.5,
      reviews: 99,
      distance: '2.9 km',
      distanceKm: 2.9,
      onTime: 89,
      price: 1500,
      available: '09:30 AM',
      cancellationRate: 11,
      reliabilityScore: 89,
      badge: 'Reliable',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Hidden leak detection',
        'Geyser & heater installation',
        'Same-day service guarantee',
      ],
    ),
    ProviderModel(
      name: 'Zubair Plumbing Works',
      city: 'Karachi',
      serviceCategory: 'Plumbing',
      rating: 4.3,
      reviews: 63,
      distance: '4.4 km',
      distanceKm: 4.4,
      onTime: 83,
      price: 1200,
      available: '10:00 AM',
      cancellationRate: 17,
      reliabilityScore: 83,
      badge: 'Lowest Price',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Cheapest plumbing in area',
        'Block clearing specialist',
        'Overhead & underground tank repairs',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  KARACHI — BEAUTICIAN  (5)           ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'Glow Studio by Nadia',
      city: 'Karachi',
      serviceCategory: 'Beautician',
      rating: 4.9,
      reviews: 412,
      distance: '1.1 km',
      distanceKm: 1.1,
      onTime: 97,
      price: 2200,
      available: '10:00 AM',
      cancellationRate: 2,
      reliabilityScore: 98,
      badge: 'Highest Rated',
      badgeColor: Color(0xFFFF80AB),
      reasons: [
        'Top-rated beautician in Karachi',
        'Bridal & party makeup expert',
        'Home visit available',
        'Premium international products',
      ],
    ),
    ProviderModel(
      name: 'Beauty Hub KHI',
      city: 'Karachi',
      serviceCategory: 'Beautician',
      rating: 4.6,
      reviews: 231,
      distance: '2.5 km',
      distanceKm: 2.5,
      onTime: 91,
      price: 1600,
      available: '11:00 AM',
      cancellationRate: 9,
      reliabilityScore: 91,
      badge: 'Budget Friendly',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Affordable beauty packages',
        'Hair, skin & nails specialist',
        'Experienced certified team',
        'DHA & Clifton area coverage',
      ],
    ),
    ProviderModel(
      name: 'Zara Glam Studio',
      city: 'Karachi',
      serviceCategory: 'Beautician',
      rating: 4.7,
      reviews: 287,
      distance: '1.8 km',
      distanceKm: 1.8,
      onTime: 93,
      price: 2000,
      available: '10:30 AM',
      cancellationRate: 6,
      reliabilityScore: 93,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Trending hair & color treatments',
        'L\'Oreal & Schwarzkopf products',
        'Bridal packages available',
        'Gulshan & Johar specialist',
      ],
    ),
    ProviderModel(
      name: 'Rania Beauty Lounge',
      city: 'Karachi',
      serviceCategory: 'Beautician',
      rating: 4.5,
      reviews: 164,
      distance: '3.1 km',
      distanceKm: 3.1,
      onTime: 89,
      price: 1400,
      available: '11:30 AM',
      cancellationRate: 11,
      reliabilityScore: 89,
      badge: 'Good Value',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Great value beauty service',
        'Mehndi & waxing specialist',
        'Flexible timing available',
      ],
    ),
    ProviderModel(
      name: 'Luxe Look by Maham',
      city: 'Karachi',
      serviceCategory: 'Beautician',
      rating: 4.8,
      reviews: 341,
      distance: '2.2 km',
      distanceKm: 2.2,
      onTime: 95,
      price: 2800,
      available: '09:30 AM',
      cancellationRate: 4,
      reliabilityScore: 95,
      badge: 'Premium',
      badgeColor: Color(0xFFFF80AB),
      reasons: [
        'Premium bridal specialist',
        'HD makeup & airbrush expert',
        'Celebrity clientele experience',
        'Morning slots available',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  KARACHI — TUTOR  (5)                ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'Sir Kamran — ProTutor',
      city: 'Karachi',
      serviceCategory: 'Tutor',
      rating: 4.9,
      reviews: 387,
      distance: '2.8 km',
      distanceKm: 2.8,
      onTime: 97,
      price: 1500,
      available: '04:00 PM',
      cancellationRate: 2,
      reliabilityScore: 97,
      badge: 'Top Pick',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'O & A Level Maths specialist',
        'Consistent 90%+ student results',
        'Flexible morning & evening slots',
        'Affordable per-session rate',
      ],
    ),
    ProviderModel(
      name: 'Learn With Zara',
      city: 'Karachi',
      serviceCategory: 'Tutor',
      rating: 4.7,
      reviews: 214,
      distance: '1.5 km',
      distanceKm: 1.5,
      onTime: 93,
      price: 1000,
      available: '05:00 PM',
      cancellationRate: 6,
      reliabilityScore: 93,
      badge: 'Nearest',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Closest tutor to you',
        'Maths & Science Matric specialist',
        'Budget-friendly rate',
        'Female tutor — home visit',
      ],
    ),
    ProviderModel(
      name: 'EduRise Academy — Bilal',
      city: 'Karachi',
      serviceCategory: 'Tutor',
      rating: 4.6,
      reviews: 178,
      distance: '3.4 km',
      distanceKm: 3.4,
      onTime: 91,
      price: 1200,
      available: '03:30 PM',
      cancellationRate: 8,
      reliabilityScore: 91,
      badge: 'Highly Rated',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Physics & Chemistry expert',
        'IBA & LUMS entry test prep',
        'Group & individual sessions',
        'Online & in-person available',
      ],
    ),
    ProviderModel(
      name: 'Ms. Hina — English Tutor',
      city: 'Karachi',
      serviceCategory: 'Tutor',
      rating: 4.8,
      reviews: 263,
      distance: '2.1 km',
      distanceKm: 2.1,
      onTime: 95,
      price: 900,
      available: '04:30 PM',
      cancellationRate: 4,
      reliabilityScore: 95,
      badge: 'Best Value',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'IELTS & English communication',
        'Best value per session',
        'Primary to Matric level',
        'Patient teaching style',
      ],
    ),
    ProviderModel(
      name: 'Star Tutors Network KHI',
      city: 'Karachi',
      serviceCategory: 'Tutor',
      rating: 4.5,
      reviews: 142,
      distance: '4.0 km',
      distanceKm: 4.0,
      onTime: 88,
      price: 1800,
      available: '05:30 PM',
      cancellationRate: 12,
      reliabilityScore: 88,
      badge: 'Multi-Subject',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'All subjects covered',
        'Network of 20+ tutors',
        'A Level & Matric board',
        'Evening slots available',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  KARACHI — CLEANING  (3)             ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'CleanPro KHI',
      city: 'Karachi',
      serviceCategory: 'Cleaning',
      rating: 4.8,
      reviews: 267,
      distance: '1.9 km',
      distanceKm: 1.9,
      onTime: 95,
      price: 3500,
      available: '08:00 AM',
      cancellationRate: 4,
      reliabilityScore: 95,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Deep home cleaning specialist',
        'Eco-friendly products used',
        'Uniformed & verified staff',
        'Post-construction cleaning',
      ],
    ),
    ProviderModel(
      name: 'Safai Masters KHI',
      city: 'Karachi',
      serviceCategory: 'Cleaning',
      rating: 4.5,
      reviews: 149,
      distance: '2.7 km',
      distanceKm: 2.7,
      onTime: 89,
      price: 2500,
      available: '09:00 AM',
      cancellationRate: 10,
      reliabilityScore: 89,
      badge: 'Budget Friendly',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Affordable home cleaning',
        'Bathroom & kitchen focus',
        'Flexible scheduling',
      ],
    ),
    ProviderModel(
      name: 'SparkleHome Services',
      city: 'Karachi',
      serviceCategory: 'Cleaning',
      rating: 4.6,
      reviews: 188,
      distance: '3.3 km',
      distanceKm: 3.3,
      onTime: 91,
      price: 4000,
      available: '07:30 AM',
      cancellationRate: 7,
      reliabilityScore: 91,
      badge: 'Premium',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Premium villa & apartment cleaning',
        'Sofa & carpet shampooing',
        'Disinfection service included',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  KARACHI — MECHANIC  (3)             ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'AutoCare KHI — Salman',
      city: 'Karachi',
      serviceCategory: 'Mechanic',
      rating: 4.7,
      reviews: 298,
      distance: '2.3 km',
      distanceKm: 2.3,
      onTime: 92,
      price: 2000,
      available: '09:00 AM',
      cancellationRate: 7,
      reliabilityScore: 92,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Multi-brand certified mechanic',
        'Doorstep service available',
        'Transparent parts pricing',
        'Suzuki & Toyota specialist',
      ],
    ),
    ProviderModel(
      name: 'Garage Pro KHI',
      city: 'Karachi',
      serviceCategory: 'Mechanic',
      rating: 4.5,
      reviews: 173,
      distance: '3.6 km',
      distanceKm: 3.6,
      onTime: 88,
      price: 1600,
      available: '10:00 AM',
      cancellationRate: 11,
      reliabilityScore: 88,
      badge: 'Budget Friendly',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Affordable engine diagnostics',
        'Oil change & tyre rotation',
        'Bike & car mechanic',
      ],
    ),
    ProviderModel(
      name: 'SpeedFix Motors KHI',
      city: 'Karachi',
      serviceCategory: 'Mechanic',
      rating: 4.6,
      reviews: 211,
      distance: '1.7 km',
      distanceKm: 1.7,
      onTime: 93,
      price: 2500,
      available: '08:30 AM',
      cancellationRate: 6,
      reliabilityScore: 93,
      badge: 'Fast Response',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Fastest roadside mechanic',
        'Battery & electrical expert',
        'AC gas for cars available',
        'DHA & Clifton coverage',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  KARACHI — SHIFTING  (2)             ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'SafeMove KHI',
      city: 'Karachi',
      serviceCategory: 'Shifting',
      rating: 4.6,
      reviews: 192,
      distance: '3.8 km',
      distanceKm: 3.8,
      onTime: 91,
      price: 9000,
      available: '07:00 AM',
      cancellationRate: 8,
      reliabilityScore: 91,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Insured house shifting',
        'Large truck + mini truck fleet',
        'Packing materials included',
        'Careful furniture handling',
      ],
    ),
    ProviderModel(
      name: 'Quick Shift KHI',
      city: 'Karachi',
      serviceCategory: 'Shifting',
      rating: 4.4,
      reviews: 114,
      distance: '4.5 km',
      distanceKm: 4.5,
      onTime: 87,
      price: 7000,
      available: '08:00 AM',
      cancellationRate: 12,
      reliabilityScore: 87,
      badge: 'Budget Friendly',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Most affordable mover in KHI',
        'Small apartment specialist',
        'Same-day shifting available',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  ISLAMABAD — AC REPAIR  (5)          ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'CapitalCool AC — Waqas',
      city: 'Islamabad',
      serviceCategory: 'AC Repair',
      rating: 4.8,
      reviews: 241,
      distance: '2.2 km',
      distanceKm: 2.2,
      onTime: 95,
      price: 2700,
      available: '09:30 AM',
      cancellationRate: 4,
      reliabilityScore: 95,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Top-rated AC service in ISB',
        'All brands: Haier, Dawlance, Gree',
        'F & G sector specialist',
        'Low cancellation record',
      ],
    ),
    ProviderModel(
      name: 'IslamaCool Services',
      city: 'Islamabad',
      serviceCategory: 'AC Repair',
      rating: 4.6,
      reviews: 178,
      distance: '3.0 km',
      distanceKm: 3.0,
      onTime: 91,
      price: 2400,
      available: '10:30 AM',
      cancellationRate: 9,
      reliabilityScore: 91,
      badge: 'Budget Friendly',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Affordable gas charging (R-22 & R-410A)',
        'Split & window AC expert',
        'Bahria & E-11 coverage',
        'Good customer reviews',
      ],
    ),
    ProviderModel(
      name: 'Arctic ISB Tech',
      city: 'Islamabad',
      serviceCategory: 'AC Repair',
      rating: 4.5,
      reviews: 123,
      distance: '1.8 km',
      distanceKm: 1.8,
      onTime: 88,
      price: 2900,
      available: '11:00 AM',
      cancellationRate: 11,
      reliabilityScore: 88,
      badge: 'Nearest',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Closest AC technician to you',
        'Inverter compressor specialist',
        'PCB board repair & replacement',
      ],
    ),
    ProviderModel(
      name: 'Malik AC Services ISB',
      city: 'Islamabad',
      serviceCategory: 'AC Repair',
      rating: 4.4,
      reviews: 98,
      distance: '4.1 km',
      distanceKm: 4.1,
      onTime: 85,
      price: 2100,
      available: '08:00 AM',
      cancellationRate: 15,
      reliabilityScore: 85,
      badge: 'Early Bird',
      badgeColor: Color(0xFF66BB6A),
      reasons: [
        'Earliest 8:00 AM slot',
        'Budget AC repair',
        'Rawalpindi & I-14 coverage',
      ],
    ),
    ProviderModel(
      name: 'PindiCool Experts',
      city: 'Islamabad',
      serviceCategory: 'AC Repair',
      rating: 4.7,
      reviews: 189,
      distance: '2.7 km',
      distanceKm: 2.7,
      onTime: 93,
      price: 2500,
      available: '10:00 AM',
      cancellationRate: 6,
      reliabilityScore: 93,
      badge: 'Highly Reliable',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Top-rated Rawalpindi AC service',
        'Annual AMC contracts available',
        'Cassette & ducted AC expert',
        'Commercial & residential',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  ISLAMABAD — ELECTRICIAN  (4)        ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'Volt Masters ISB — Asif',
      city: 'Islamabad',
      serviceCategory: 'Electrician',
      rating: 4.9,
      reviews: 312,
      distance: '1.7 km',
      distanceKm: 1.7,
      onTime: 96,
      price: 2000,
      available: '08:30 AM',
      cancellationRate: 3,
      reliabilityScore: 96,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Highest rated electrician in ISB',
        'Licensed & fully insured',
        'Wiring, UPS & solar expert',
        'Near-perfect punctuality',
      ],
    ),
    ProviderModel(
      name: 'CurrentFix ISB',
      city: 'Islamabad',
      serviceCategory: 'Electrician',
      rating: 4.6,
      reviews: 167,
      distance: '2.6 km',
      distanceKm: 2.6,
      onTime: 91,
      price: 1700,
      available: '09:00 AM',
      cancellationRate: 8,
      reliabilityScore: 91,
      badge: 'Budget Friendly',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Affordable wiring & repairs',
        'DB board replacement',
        'Bahria Town specialist',
      ],
    ),
    ProviderModel(
      name: 'Sohail Electric Works ISB',
      city: 'Islamabad',
      serviceCategory: 'Electrician',
      rating: 4.7,
      reviews: 204,
      distance: '2.1 km',
      distanceKm: 2.1,
      onTime: 93,
      price: 2200,
      available: '09:30 AM',
      cancellationRate: 6,
      reliabilityScore: 93,
      badge: 'Highly Reliable',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Commercial & residential expert',
        'WAPDA-approved connections',
        'I-8 & G-11 area specialist',
        'Emergency call-out service',
      ],
    ),
    ProviderModel(
      name: 'TechVolt ISB',
      city: 'Islamabad',
      serviceCategory: 'Electrician',
      rating: 4.5,
      reviews: 131,
      distance: '3.5 km',
      distanceKm: 3.5,
      onTime: 88,
      price: 1500,
      available: '10:00 AM',
      cancellationRate: 12,
      reliabilityScore: 88,
      badge: 'Budget Option',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Most affordable in Rawalpindi',
        'Ceiling fan & light repairs',
        'Same-day response',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  ISLAMABAD — PLUMBING  (5)           ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'FlowFix ISB — Usman',
      city: 'Islamabad',
      serviceCategory: 'Plumbing',
      rating: 4.7,
      reviews: 198,
      distance: '2.5 km',
      distanceKm: 2.5,
      onTime: 93,
      price: 1700,
      available: '08:00 AM',
      cancellationRate: 6,
      reliabilityScore: 93,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Emergency plumbing response',
        'Motor & submersible pump expert',
        'F & G sector coverage',
        'Reliable track record',
      ],
    ),
    ProviderModel(
      name: 'RawalpindiPipe Pros',
      city: 'Islamabad',
      serviceCategory: 'Plumbing',
      rating: 4.5,
      reviews: 142,
      distance: '3.3 km',
      distanceKm: 3.3,
      onTime: 89,
      price: 1400,
      available: '09:00 AM',
      cancellationRate: 11,
      reliabilityScore: 89,
      badge: 'Budget Friendly',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Affordable plumbing services',
        'Drain unblocking specialist',
        'Rawalpindi area coverage',
      ],
    ),
    ProviderModel(
      name: 'IslamaPipe Solutions',
      city: 'Islamabad',
      serviceCategory: 'Plumbing',
      rating: 4.6,
      reviews: 163,
      distance: '1.9 km',
      distanceKm: 1.9,
      onTime: 91,
      price: 1900,
      available: '08:30 AM',
      cancellationRate: 8,
      reliabilityScore: 91,
      badge: 'Nearest',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Closest plumber to you',
        'Bathroom renovation expert',
        'Geyser & solar heater install',
        'Bahria Town specialist',
      ],
    ),
    ProviderModel(
      name: 'Master Shafiq Plumber ISB',
      city: 'Islamabad',
      serviceCategory: 'Plumbing',
      rating: 4.4,
      reviews: 96,
      distance: '4.2 km',
      distanceKm: 4.2,
      onTime: 84,
      price: 1200,
      available: '10:00 AM',
      cancellationRate: 16,
      reliabilityScore: 84,
      badge: 'Lowest Price',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Lowest price in ISB',
        'Basic leak & tap repairs',
        'I-14 & I-10 sector coverage',
      ],
    ),
    ProviderModel(
      name: 'AquaTech ISB',
      city: 'Islamabad',
      serviceCategory: 'Plumbing',
      rating: 4.7,
      reviews: 177,
      distance: '2.2 km',
      distanceKm: 2.2,
      onTime: 92,
      price: 2000,
      available: '08:00 AM',
      cancellationRate: 7,
      reliabilityScore: 92,
      badge: 'Reliable',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Underground water tank specialist',
        'New construction plumbing',
        'PWD & DHA ISB coverage',
        'Prompt & professional',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  ISLAMABAD — BEAUTICIAN  (5)         ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'Falak Beauty Lounge ISB',
      city: 'Islamabad',
      serviceCategory: 'Beautician',
      rating: 4.8,
      reviews: 296,
      distance: '2.0 km',
      distanceKm: 2.0,
      onTime: 95,
      price: 2000,
      available: '10:00 AM',
      cancellationRate: 4,
      reliabilityScore: 95,
      badge: 'Top Pick',
      badgeColor: Color(0xFFFF80AB),
      reasons: [
        'Top-rated beautician in ISB',
        'Bridal & event makeup expert',
        'Home visit available in F-7/F-10',
        'Premium products used',
      ],
    ),
    ProviderModel(
      name: 'Glow Lab ISB',
      city: 'Islamabad',
      serviceCategory: 'Beautician',
      rating: 4.6,
      reviews: 187,
      distance: '1.6 km',
      distanceKm: 1.6,
      onTime: 91,
      price: 1600,
      available: '11:00 AM',
      cancellationRate: 8,
      reliabilityScore: 91,
      badge: 'Nearest',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Closest beautician to you',
        'Hair color & keratin specialist',
        'Affordable packages',
        'Bahria & Blue Area coverage',
      ],
    ),
    ProviderModel(
      name: 'Aroha Beauty Studio ISB',
      city: 'Islamabad',
      serviceCategory: 'Beautician',
      rating: 4.7,
      reviews: 234,
      distance: '2.8 km',
      distanceKm: 2.8,
      onTime: 93,
      price: 2500,
      available: '10:30 AM',
      cancellationRate: 5,
      reliabilityScore: 93,
      badge: 'Highly Reliable',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Luxury salon experience at home',
        'Airbrush & HD makeup',
        'Strong reliability record',
      ],
    ),
    ProviderModel(
      name: 'Noor Beauty ISB',
      city: 'Islamabad',
      serviceCategory: 'Beautician',
      rating: 4.5,
      reviews: 148,
      distance: '3.2 km',
      distanceKm: 3.2,
      onTime: 89,
      price: 1400,
      available: '11:30 AM',
      cancellationRate: 10,
      reliabilityScore: 89,
      badge: 'Budget Friendly',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Affordable mehndi & waxing',
        'Maternity & bridal packages',
        'Rawalpindi area coverage',
      ],
    ),
    ProviderModel(
      name: 'Saima Glam House ISB',
      city: 'Islamabad',
      serviceCategory: 'Beautician',
      rating: 4.8,
      reviews: 271,
      distance: '1.4 km',
      distanceKm: 1.4,
      onTime: 95,
      price: 2200,
      available: '10:00 AM',
      cancellationRate: 4,
      reliabilityScore: 95,
      badge: 'Premium',
      badgeColor: Color(0xFFFF80AB),
      reasons: [
        'Premium home salon ISB',
        'Eyebrow shaping & lash expert',
        'Hydrafacial treatment available',
        'G-sector coverage',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  ISLAMABAD — TUTOR  (5)              ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'EduPeak ISB — Sir Hassan',
      city: 'Islamabad',
      serviceCategory: 'Tutor',
      rating: 4.9,
      reviews: 378,
      distance: '2.1 km',
      distanceKm: 2.1,
      onTime: 97,
      price: 1800,
      available: '03:30 PM',
      cancellationRate: 2,
      reliabilityScore: 97,
      badge: 'Highest Rated',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Best tutor in Islamabad',
        'CSS & MDCAT preparation',
        'O & A Level all subjects',
        'Flexible home & online sessions',
      ],
    ),
    ProviderModel(
      name: 'BrightMind ISB',
      city: 'Islamabad',
      serviceCategory: 'Tutor',
      rating: 4.7,
      reviews: 212,
      distance: '1.9 km',
      distanceKm: 1.9,
      onTime: 93,
      price: 1400,
      available: '04:00 PM',
      cancellationRate: 6,
      reliabilityScore: 93,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Maths, Physics & Chemistry',
        'IBA & NUST entry test prep',
        'Competitive pricing',
        'F-7 & G-10 area',
      ],
    ),
    ProviderModel(
      name: 'Ms. Sara — English & Urdu',
      city: 'Islamabad',
      serviceCategory: 'Tutor',
      rating: 4.8,
      reviews: 256,
      distance: '2.5 km',
      distanceKm: 2.5,
      onTime: 95,
      price: 1100,
      available: '04:30 PM',
      cancellationRate: 4,
      reliabilityScore: 95,
      badge: 'Best Value',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'English literature & Urdu expert',
        'Best value per session in ISB',
        'Primary to intermediate level',
        'Home visit available',
      ],
    ),
    ProviderModel(
      name: 'Capital Tutors Network ISB',
      city: 'Islamabad',
      serviceCategory: 'Tutor',
      rating: 4.5,
      reviews: 163,
      distance: '3.7 km',
      distanceKm: 3.7,
      onTime: 89,
      price: 2000,
      available: '05:00 PM',
      cancellationRate: 10,
      reliabilityScore: 89,
      badge: 'Multi-Subject',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Network of 15+ qualified tutors',
        'All subjects & all boards',
        'Rawalpindi coverage included',
      ],
    ),
    ProviderModel(
      name: 'AcademiaPro ISB',
      city: 'Islamabad',
      serviceCategory: 'Tutor',
      rating: 4.6,
      reviews: 191,
      distance: '2.9 km',
      distanceKm: 2.9,
      onTime: 91,
      price: 1600,
      available: '03:00 PM',
      cancellationRate: 8,
      reliabilityScore: 91,
      badge: 'Exam Prep',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'ECAT & MDCAT specialist',
        'Biology & Chemistry focus',
        'Bahria Town ISB coverage',
        'Weekend batches available',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  LAHORE — AC REPAIR  (5)             ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'LahoreAC Pro — Shahid',
      city: 'Lahore',
      serviceCategory: 'AC Repair',
      rating: 4.8,
      reviews: 284,
      distance: '1.8 km',
      distanceKm: 1.8,
      onTime: 94,
      price: 2300,
      available: '09:30 AM',
      cancellationRate: 5,
      reliabilityScore: 94,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Most trusted AC service in Lahore',
        'Inverter & non-inverter expert',
        'DHA & Johar Town specialist',
        'Low cancellation rate',
      ],
    ),
    ProviderModel(
      name: 'CoolBreeze Lahore',
      city: 'Lahore',
      serviceCategory: 'AC Repair',
      rating: 4.5,
      reviews: 156,
      distance: '3.3 km',
      distanceKm: 3.3,
      onTime: 88,
      price: 1900,
      available: '10:30 AM',
      cancellationRate: 13,
      reliabilityScore: 88,
      badge: 'Budget Friendly',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Most affordable in Lahore',
        'R-22 & R-410 gas specialist',
        'Weekend bookings available',
        'Gulberg & Model Town coverage',
      ],
    ),
    ProviderModel(
      name: 'FrostFix Lahore',
      city: 'Lahore',
      serviceCategory: 'AC Repair',
      rating: 4.6,
      reviews: 201,
      distance: '2.3 km',
      distanceKm: 2.3,
      onTime: 92,
      price: 2500,
      available: '10:00 AM',
      cancellationRate: 7,
      reliabilityScore: 92,
      badge: 'Highly Reliable',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Strong reliability (92% on-time)',
        'Haier & PEL brand expert',
        'Annual maintenance available',
        'Bahria Town Lahore specialist',
      ],
    ),
    ProviderModel(
      name: 'IceCool Services LHR',
      city: 'Lahore',
      serviceCategory: 'AC Repair',
      rating: 4.4,
      reviews: 113,
      distance: '4.2 km',
      distanceKm: 4.2,
      onTime: 86,
      price: 1700,
      available: '08:30 AM',
      cancellationRate: 14,
      reliabilityScore: 86,
      badge: 'Earliest Slot',
      badgeColor: Color(0xFF66BB6A),
      reasons: [
        'Earliest 8:30 AM slot',
        'Affordable gas charging',
        'Iqbal Town & Faisal Town coverage',
      ],
    ),
    ProviderModel(
      name: 'AirMaster LHR',
      city: 'Lahore',
      serviceCategory: 'AC Repair',
      rating: 4.7,
      reviews: 237,
      distance: '2.0 km',
      distanceKm: 2.0,
      onTime: 93,
      price: 2600,
      available: '10:00 AM',
      cancellationRate: 6,
      reliabilityScore: 93,
      badge: 'Premium',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Premium AC service',
        'Cassette & split AC specialist',
        'Transparent pricing policy',
        'Cavalry Ground & Cantt area',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  LAHORE — ELECTRICIAN  (5)           ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'PowerLine LHR — Junaid',
      city: 'Lahore',
      serviceCategory: 'Electrician',
      rating: 4.8,
      reviews: 263,
      distance: '1.6 km',
      distanceKm: 1.6,
      onTime: 93,
      price: 1700,
      available: '08:30 AM',
      cancellationRate: 5,
      reliabilityScore: 93,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Highest rated electrician in LHR',
        'WAPDA-certified technician',
        'DB board & full wiring expert',
        'DHA & Gulberg specialist',
      ],
    ),
    ProviderModel(
      name: 'BrightWire Lahore',
      city: 'Lahore',
      serviceCategory: 'Electrician',
      rating: 4.6,
      reviews: 188,
      distance: '2.4 km',
      distanceKm: 2.4,
      onTime: 90,
      price: 1500,
      available: '09:00 AM',
      cancellationRate: 9,
      reliabilityScore: 90,
      badge: 'Budget Friendly',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Most affordable electrician LHR',
        'Johar Town & Township area',
        'UPS installation & repair',
      ],
    ),
    ProviderModel(
      name: 'Lahore Electric Masters',
      city: 'Lahore',
      serviceCategory: 'Electrician',
      rating: 4.7,
      reviews: 219,
      distance: '2.0 km',
      distanceKm: 2.0,
      onTime: 92,
      price: 2000,
      available: '09:00 AM',
      cancellationRate: 7,
      reliabilityScore: 92,
      badge: 'Highly Reliable',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Commercial & residential expert',
        'Solar panel wiring specialist',
        'Emergency 24/7 available',
        'Bahria & Model Town coverage',
      ],
    ),
    ProviderModel(
      name: 'ZapFix Electricals LHR',
      city: 'Lahore',
      serviceCategory: 'Electrician',
      rating: 4.4,
      reviews: 104,
      distance: '3.7 km',
      distanceKm: 3.7,
      onTime: 86,
      price: 1300,
      available: '10:00 AM',
      cancellationRate: 14,
      reliabilityScore: 86,
      badge: 'Budget Option',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Lowest price electrician',
        'Fan, light & switch repairs',
        'Iqbal Town & Faisal Town',
      ],
    ),
    ProviderModel(
      name: 'VoltEdge LHR — Kamran',
      city: 'Lahore',
      serviceCategory: 'Electrician',
      rating: 4.5,
      reviews: 152,
      distance: '2.8 km',
      distanceKm: 2.8,
      onTime: 89,
      price: 1800,
      available: '09:30 AM',
      cancellationRate: 10,
      reliabilityScore: 89,
      badge: 'Reliable',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Inverter & generator specialist',
        'Cantt & Valencia coverage',
        'Honest diagnostic charges',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  LAHORE — PLUMBING  (5)              ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'AquaPro Lahore — Riaz',
      city: 'Lahore',
      serviceCategory: 'Plumbing',
      rating: 4.7,
      reviews: 231,
      distance: '1.9 km',
      distanceKm: 1.9,
      onTime: 93,
      price: 1600,
      available: '08:00 AM',
      cancellationRate: 6,
      reliabilityScore: 93,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Emergency plumbing specialist LHR',
        'Water pump & motor expert',
        'DHA & Gulberg coverage',
        'Strong reliability record',
      ],
    ),
    ProviderModel(
      name: 'Lahore Pipe Masters',
      city: 'Lahore',
      serviceCategory: 'Plumbing',
      rating: 4.5,
      reviews: 157,
      distance: '2.7 km',
      distanceKm: 2.7,
      onTime: 88,
      price: 1300,
      available: '09:00 AM',
      cancellationRate: 12,
      reliabilityScore: 88,
      badge: 'Budget Friendly',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Most affordable plumber LHR',
        'Drain unblocking & cleaning',
        'Johar Town & Bahria coverage',
      ],
    ),
    ProviderModel(
      name: 'DrainFix LHR — Sajid',
      city: 'Lahore',
      serviceCategory: 'Plumbing',
      rating: 4.6,
      reviews: 176,
      distance: '2.2 km',
      distanceKm: 2.2,
      onTime: 90,
      price: 1800,
      available: '08:30 AM',
      cancellationRate: 9,
      reliabilityScore: 90,
      badge: 'Reliable',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Bathroom renovation specialist',
        'Geyser & solar heater install',
        'Model Town & Garden Town',
        'Neat & clean workmanship',
      ],
    ),
    ProviderModel(
      name: 'PipeLine Solutions LHR',
      city: 'Lahore',
      serviceCategory: 'Plumbing',
      rating: 4.3,
      reviews: 88,
      distance: '4.0 km',
      distanceKm: 4.0,
      onTime: 84,
      price: 1100,
      available: '10:00 AM',
      cancellationRate: 17,
      reliabilityScore: 84,
      badge: 'Lowest Price',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Cheapest plumber in Lahore',
        'Tap & flush repairs',
        'Cantt & Cavalry Ground area',
      ],
    ),
    ProviderModel(
      name: 'MasterFix Plumbing LHR',
      city: 'Lahore',
      serviceCategory: 'Plumbing',
      rating: 4.7,
      reviews: 199,
      distance: '1.6 km',
      distanceKm: 1.6,
      onTime: 92,
      price: 2000,
      available: '07:30 AM',
      cancellationRate: 7,
      reliabilityScore: 92,
      badge: 'Nearest',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Closest plumber to you',
        'Earliest morning slot (7:30 AM)',
        'Complete bathroom fit-out',
        'Valencia & Raiwind area',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  LAHORE — BEAUTICIAN  (5)            ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'Glam Lahore — Sana Studio',
      city: 'Lahore',
      serviceCategory: 'Beautician',
      rating: 4.9,
      reviews: 361,
      distance: '1.3 km',
      distanceKm: 1.3,
      onTime: 96,
      price: 2000,
      available: '10:00 AM',
      cancellationRate: 3,
      reliabilityScore: 96,
      badge: 'Highest Rated',
      badgeColor: Color(0xFFFF80AB),
      reasons: [
        'Most popular beautician in Lahore',
        'Bridal & party makeup expert',
        'Home visit — DHA & Gulberg',
        'Premium international products',
      ],
    ),
    ProviderModel(
      name: 'Luxe Looks LHR',
      city: 'Lahore',
      serviceCategory: 'Beautician',
      rating: 4.7,
      reviews: 248,
      distance: '2.1 km',
      distanceKm: 2.1,
      onTime: 93,
      price: 2500,
      available: '10:30 AM',
      cancellationRate: 6,
      reliabilityScore: 93,
      badge: 'Premium',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Airbrush & HD makeup specialist',
        'Celebrity clientele experience',
        'Model Town & Johar Town',
        'On-call bridal team available',
      ],
    ),
    ProviderModel(
      name: 'Fresh Face Studio LHR',
      city: 'Lahore',
      serviceCategory: 'Beautician',
      rating: 4.6,
      reviews: 193,
      distance: '2.8 km',
      distanceKm: 2.8,
      onTime: 90,
      price: 1500,
      available: '11:00 AM',
      cancellationRate: 9,
      reliabilityScore: 90,
      badge: 'Budget Friendly',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Affordable beauty packages',
        'Hair, skin & nail specialist',
        'Bahria & Iqbal Town area',
        'Student discount available',
      ],
    ),
    ProviderModel(
      name: 'Royal Beauty LHR — Hina',
      city: 'Lahore',
      serviceCategory: 'Beautician',
      rating: 4.8,
      reviews: 317,
      distance: '1.7 km',
      distanceKm: 1.7,
      onTime: 94,
      price: 1800,
      available: '10:00 AM',
      cancellationRate: 5,
      reliabilityScore: 94,
      badge: 'Top Pick',
      badgeColor: Color(0xFFFF80AB),
      reasons: [
        'Top-rated home beautician',
        'Mehndi & facial specialist',
        'Strong punctuality record',
        'Cantt & Cavalry Ground area',
      ],
    ),
    ProviderModel(
      name: 'Shimmer & Shine LHR',
      city: 'Lahore',
      serviceCategory: 'Beautician',
      rating: 4.5,
      reviews: 169,
      distance: '3.4 km',
      distanceKm: 3.4,
      onTime: 88,
      price: 1300,
      available: '11:30 AM',
      cancellationRate: 11,
      reliabilityScore: 88,
      badge: 'Good Value',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Great value beauty service',
        'Waxing & threading specialist',
        'Township & Ferozepur Road area',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  LAHORE — TUTOR  (5)                 ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'Sir Waleed — EduStar LHR',
      city: 'Lahore',
      serviceCategory: 'Tutor',
      rating: 4.9,
      reviews: 342,
      distance: '2.4 km',
      distanceKm: 2.4,
      onTime: 96,
      price: 1600,
      available: '04:00 PM',
      cancellationRate: 3,
      reliabilityScore: 96,
      badge: 'Top Pick',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Top-rated tutor in Lahore',
        'A Level Maths & Physics',
        'LUMS & NUST entry test prep',
        'Consistent 90%+ results',
      ],
    ),
    ProviderModel(
      name: 'LearnRight LHR — Ayesha',
      city: 'Lahore',
      serviceCategory: 'Tutor',
      rating: 4.7,
      reviews: 221,
      distance: '1.8 km',
      distanceKm: 1.8,
      onTime: 93,
      price: 1200,
      available: '04:30 PM',
      cancellationRate: 6,
      reliabilityScore: 93,
      badge: 'Nearest',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Closest tutor to you',
        'Female tutor — home visit',
        'O Level Biology & Chemistry',
        'DHA & Gulberg area',
      ],
    ),
    ProviderModel(
      name: 'MathGenius Academy LHR',
      city: 'Lahore',
      serviceCategory: 'Tutor',
      rating: 4.8,
      reviews: 289,
      distance: '2.9 km',
      distanceKm: 2.9,
      onTime: 94,
      price: 2000,
      available: '03:30 PM',
      cancellationRate: 5,
      reliabilityScore: 94,
      badge: 'Subject Expert',
      badgeColor: Color(0xFF6C4FD6),
      reasons: [
        'Maths specialist (Matric to A Level)',
        'MDCAT & ECAT math prep',
        'Proven exam improvement record',
        'Johar Town & Model Town',
      ],
    ),
    ProviderModel(
      name: 'Ms. Amna — Science Tutor LHR',
      city: 'Lahore',
      serviceCategory: 'Tutor',
      rating: 4.7,
      reviews: 198,
      distance: '2.0 km',
      distanceKm: 2.0,
      onTime: 92,
      price: 1100,
      available: '05:00 PM',
      cancellationRate: 7,
      reliabilityScore: 92,
      badge: 'Best Value',
      badgeColor: Color(0xFF00C2D4),
      reasons: [
        'Physics & Biology specialist',
        'Best value in Lahore',
        'Primary to FSc level',
        'Patient & exam-focused',
      ],
    ),
    ProviderModel(
      name: 'Lahore Tutors Network',
      city: 'Lahore',
      serviceCategory: 'Tutor',
      rating: 4.5,
      reviews: 167,
      distance: '4.1 km',
      distanceKm: 4.1,
      onTime: 88,
      price: 2200,
      available: '05:30 PM',
      cancellationRate: 11,
      reliabilityScore: 88,
      badge: 'Multi-Subject',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Network of 25+ qualified tutors',
        'All subjects — all boards',
        'Online & home sessions',
        'Bahria & Township coverage',
      ],
    ),

    // ╔═══════════════════════════════════════╗
    // ║  LAHORE — CLEANING / MECHANIC  (3)   ║
    // ╚═══════════════════════════════════════╝
    ProviderModel(
      name: 'CleanHome LHR',
      city: 'Lahore',
      serviceCategory: 'Cleaning',
      rating: 4.7,
      reviews: 218,
      distance: '2.2 km',
      distanceKm: 2.2,
      onTime: 93,
      price: 3200,
      available: '08:00 AM',
      cancellationRate: 6,
      reliabilityScore: 93,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Deep cleaning specialist LHR',
        'Eco-friendly products',
        'Sofa & carpet shampooing',
        'DHA & Gulberg coverage',
      ],
    ),
    ProviderModel(
      name: 'AutoFix Lahore — Rashid',
      city: 'Lahore',
      serviceCategory: 'Mechanic',
      rating: 4.6,
      reviews: 243,
      distance: '2.6 km',
      distanceKm: 2.6,
      onTime: 91,
      price: 1800,
      available: '09:00 AM',
      cancellationRate: 8,
      reliabilityScore: 91,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Multi-brand car mechanic',
        'Doorstep service Lahore',
        'Honda & Toyota expert',
        'Transparent repair pricing',
      ],
    ),
    ProviderModel(
      name: 'HomeShift LHR',
      city: 'Lahore',
      serviceCategory: 'Shifting',
      rating: 4.5,
      reviews: 148,
      distance: '3.5 km',
      distanceKm: 3.5,
      onTime: 89,
      price: 8500,
      available: '07:00 AM',
      cancellationRate: 10,
      reliabilityScore: 89,
      badge: 'Top Pick',
      badgeColor: Color(0xFF185FA5),
      reasons: [
        'Insured furniture shifting LHR',
        'Truck + Mazda fleet',
        'Packing & unpacking available',
        'DHA & Johar Town specialist',
      ],
    ),
  ]; // end providers
}
