// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWsnNtWLMYBJpmTBQfRvivpGhv2fZE3uw',
    appId: '1:1024025094886:web:cd5d59ad4dd69c1ea22927',
    messagingSenderId: '1024025094886',
    projectId: 'prism-ai-app-1e371',
    authDomain: 'prism-ai-app-1e371.firebaseapp.com',
    storageBucket: 'prism-ai-app-1e371.firebasestorage.app',
    measurementId: 'G-VL4XZDFP1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnt8RgOIIP5ooTwevwjZbcy6Hedv-xAtI',
    appId: '1:1024025094886:android:3c189f3eebcfa30da22927',
    messagingSenderId: '1024025094886',
    projectId: 'prism-ai-app-1e371',
    storageBucket: 'prism-ai-app-1e371.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAukvHTCe4-K80eABXrAyOU6Pz1GeMhVt0',
    appId: '1:1024025094886:ios:5765d1eed68e9a86a22927',
    messagingSenderId: '1024025094886',
    projectId: 'prism-ai-app-1e371',
    storageBucket: 'prism-ai-app-1e371.firebasestorage.app',
    iosBundleId: 'com.example.prismAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAukvHTCe4-K80eABXrAyOU6Pz1GeMhVt0',
    appId: '1:1024025094886:ios:5765d1eed68e9a86a22927',
    messagingSenderId: '1024025094886',
    projectId: 'prism-ai-app-1e371',
    storageBucket: 'prism-ai-app-1e371.firebasestorage.app',
    iosBundleId: 'com.example.prismAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWsnNtWLMYBJpmTBQfRvivpGhv2fZE3uw',
    appId: '1:1024025094886:web:6f930e4c5f3f0e1da22927',
    messagingSenderId: '1024025094886',
    projectId: 'prism-ai-app-1e371',
    authDomain: 'prism-ai-app-1e371.firebaseapp.com',
    storageBucket: 'prism-ai-app-1e371.firebasestorage.app',
    measurementId: 'G-L5YZ3DLY0S',
  );
}
